# .github/workflows/backend-ci.yml
name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packages/backend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'packages/backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: crypticity_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Lint
      run: yarn workspace @crypto-city/backend lint
      
    - name: Run tests
      run: yarn workspace @crypto-city/backend test
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/crypticity_test
        NODE_ENV: test
