# .github/workflows/frontend-ci.yml
name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packages/frontend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'packages/frontend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Lint
      run: npm run lint --workspace=@crypto-city/frontend
      
    - name: Test
      run: npm run test --workspace=@crypto-city/frontend
      
    - name: Build
      run: npm run build --workspace=@crypto-city/frontend