# .github/workflows/frontend-ci.yml
name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'packages/frontend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'packages/frontend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Lint
      run: yarn workspace @crypto-city/frontend lint
      
    - name: Test
      run: yarn workspace @crypto-city/frontend test
      
    - name: Build
      run: yarn workspace @crypto-city/frontend build
